---
- name: Download elasticsearch .deb package
  get_url:
    url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.3.0.deb
    dest: /tmp/elasticsearch-5.3.0.deb

- name: Install elasticsearch .deb package
  apt:
    deb: /tmp/elasticsearch-5.3.0.deb

- name: Copy Raspberry Pi JVM options configuration
  template: src=jvm.options dest=/etc/elasticsearch/jvm.options

- name: Fix /etc/elasticsearch access rights
  file:
    path: /etc/elasticsearch
    owner: elasticsearch
    group: elasticsearch

- name: Allow http api within local lan
  ufw:
    proto: tcp
    port: 9200
    rule: allow
    src: 192.168.125.0/24

- name: start elasticsearch
  service: name=elasticsearch state=started enabled=yes